### ISSUE TITLE
There is a bug when you click the number in the center of the dialog.

### ISSUE THREAD

**Issue by ChenJia-X** [ch-muhammad-adil/Android-Material-Picker-Dialog#1]
In one plus 5, Android 7.1.1, when I click the number, there is a crash.
From the following information, we know that we need to add `vibrate permission` in the AndroidManifest.xml.
So you can add this into README.

## The following is the error information.
java.lang.SecurityException: **Requires VIBRATE permission**
                                                                             at android.os.Parcel.readException(Parcel.java:1684)
                                                                             at android.os.Parcel.readException(Parcel.java:1637)
                                                                             at android.os.IVibratorService$Stub$Proxy.vibrate(IVibratorService.java:146)
                                                                             at android.os.SystemVibrator.vibrate(SystemVibrator.java:68)
                                                                             at android.os.Vibrator.vibrate(Vibrator.java:80)
                                                                             at android.os.Vibrator.vibrate(Vibrator.java:65)
                                                                             at adil.dev.lib.materialnumberpicker.adapter.NumberPickerAdapter$DialogViewHolder.onClick(NumberPickerAdapter.java:110)
                                                                             at android.view.View.performClick(View.java:5669)
                                                                             at android.view.View$PerformClick.run(View.java:22540)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6334)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by ch-muhammad-adil** [comment]
Hey @ChenJia-X , Thanks for letting me know. I will take a look.
